### This file acts as the global config across the website.
### Any variables in this file can be accessed in other files using
###    `{{ site.variable }}`


######################
# Site configuration #
######################
# This title will display across the website
title: "Mentor Matching Online"
# This description is predominantly for Search Engine Optimisation
description: "An online service for mentor matching."
# Instead of "author", have the organisation name as the default
author: "John Peart"
organisation: "Mentor Matching Online"
email: "info@mentormatching.online"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://assets.mentormatching.online"

##################################
# Analytics and domain ownership #
##################################
# Google settings
google-site-verification: ""

##################
# Build settings #
##################
permalink: pretty
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass

plugins:
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-feed
- jekyll-redirect-from


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/